// BH1750 - Version: 1.1.4
#include <BH1750.h>

// BH1750FVI - Version: Latest 
// #include <BH1750FVI.h>
BH1750 lightMeter;

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Nikhil Task ECD"
  https://create.arduino.cc/cloud/things/6ad03b89-addb-4679-b290-4ff806627a53 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudIlluminance terrarium_sunlight;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
    Wire.begin();

  lightMeter.begin();
  Serial.println(F("BH1750 Test"));
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  float light = lightMeter.readLightLevel();
  Serial.print("Light: ");
  Serial.print(light);
  Serial.println(" lx");
  delay(1000);
  terrarium_sunlight = light;
}


/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  // Add your code here to act upon Light change
  
}









